# Generated by Django 5.0.6 on 2024-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='city',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_icon',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(default='background.jpg', max_length=200, null=True),
        ),
    ]
