# Generated by Django 5.0.6 on 2024-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_city_destination_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='background.jpg', null=True, upload_to=''),
        ),
    ]
