# Generated by Django 5.0.6 on 2024-07-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_customer_email_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='mail@mail.com', max_length=254, unique=True),
        ),
    ]
